esphome:
  name: soil1
  platform: ESP32
  board: lolin_d32
  includes:
    - "Adafruit_seesaw.h"
    - "Adafruit_seesaw.cpp"
    - "soil.h"

wifi:
  ssid: "Lillen4"
  password: "tilda?4321"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soil1 Fallback Hotspot"
    password: "pYRX6HHZYbes"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "tilda4321"

ota:
  password: "tilda4321"

i2c:
  sda: 21
  scl: 22
  scan: True

#Polling 15 sec set in soil.h

sensor:  
  - platform: custom
    lambda: |-
      auto soil_comp = new SOIL();
      App.register_component(soil_comp);
      return {soil_comp->temperature_sensor, soil_comp->humidity_sensor};
    sensors:
    - name: "Soil Temperature"
      unit_of_measurement: °C
      accuracy_decimals: 2
    - name: "Soil Humidity"
      accuracy_decimals: 2

